# Generated by Django 4.2.5 on 2023-09-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('inclass', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
